repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint
        pass_filenames: false
        args:
          - ./inventory/cmd
          - ./order/cmd
          - ./payment/cmd


