// Code generated for Akbar-cmd service
// © Akbar-cmd 2025.
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Akbar-cmd/raketa-factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrderRepository) CreateOrder(ctx context.Context, order model.OrderData) (model.OrderCreationInfo, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 model.OrderCreationInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderData) (model.OrderCreationInfo, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderData) model.OrderCreationInfo); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(model.OrderCreationInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.OrderData) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.OrderData
func (_e *OrderRepository_Expecter) CreateOrder(ctx interface{}, order interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(ctx context.Context, order model.OrderData)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderData))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(info model.OrderCreationInfo, err error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(info, err)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, model.OrderData) (model.OrderCreationInfo, error)) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByUuid provides a mock function with given fields: ctx, uuid
func (_m *OrderRepository) GetOrderByUuid(ctx context.Context, uuid string) (model.OrderData, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUuid")
	}

	var r0 model.OrderData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.OrderData, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.OrderData); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.OrderData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetOrderByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByUuid'
type OrderRepository_GetOrderByUuid_Call struct {
	*mock.Call
}

// GetOrderByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderRepository_Expecter) GetOrderByUuid(ctx interface{}, uuid interface{}) *OrderRepository_GetOrderByUuid_Call {
	return &OrderRepository_GetOrderByUuid_Call{Call: _e.mock.On("GetOrderByUuid", ctx, uuid)}
}

func (_c *OrderRepository_GetOrderByUuid_Call) Run(run func(ctx context.Context, uuid string)) *OrderRepository_GetOrderByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrderByUuid_Call) Return(_a0 model.OrderData, _a1 error) *OrderRepository_GetOrderByUuid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrderByUuid_Call) RunAndReturn(run func(context.Context, string) (model.OrderData, error)) *OrderRepository_GetOrderByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, uuid, updateOrder
func (_m *OrderRepository) UpdateOrder(ctx context.Context, uuid string, updateOrder model.OrderUpdateInfo) error {
	ret := _m.Called(ctx, uuid, updateOrder)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OrderUpdateInfo) error); ok {
		r0 = rf(ctx, uuid, updateOrder)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - updateOrder model.OrderUpdateInfo
func (_e *OrderRepository_Expecter) UpdateOrder(ctx interface{}, uuid interface{}, updateOrder interface{}) *OrderRepository_UpdateOrder_Call {
	return &OrderRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, uuid, updateOrder)}
}

func (_c *OrderRepository_UpdateOrder_Call) Run(run func(ctx context.Context, uuid string, updateOrder model.OrderUpdateInfo)) *OrderRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.OrderUpdateInfo))
	})
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) Return(_a0 error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) RunAndReturn(run func(context.Context, string, model.OrderUpdateInfo) error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
